; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

; Most Blue Pills require this for the 64k vs 128k flash fix
board_upload.maximum_size = 131072

; Upload Method (Change to 'serial' if using a USB-TTL adapter)
upload_protocol = stlink

lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
    SPI
    Wire